[env:esp32-s3]
platform = espressif32
board = seeed_xiao_esp32s3
framework = arduino
monitor_speed = 115200
board_build.arduino.usb_cdc = false
board_build.flash_mode = qio
board_build.partitions = default_8MB.csv

lib_extra_dirs = Lib

; This board is connected through a USB-to-UART adapter.
build_unflags = -DARDUINO_USB_CDC_ON_BOOT=1
build_flags =
    -DARDUINO_USB_CDC_ON_BOOT=0
    -Wno-deprecated
    -DCONFIG_LWIP_TCP_SND_BUF=32768
    -DCONFIG_LWIP_TCP_WND=32768
    -DARDUINO_LOOP_STACK_SIZE=24576
    -DMBEDTLS_ALLOW_PRIVATE_ACCESS
